tap "dekker1/minizinc", "git@github.com:Dekker1/homebrew-minizinc.git"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
brew "aspell"
brew "bat"
brew "bison"
brew "python@3.9"
brew "cbc"
brew "ccache"
brew "cmake"
brew "emacs", restart_service: true
brew "exa"
brew "fd"
brew "flex"
brew "fzf"
brew "gecode"
brew "gh"
brew "gnupg"
brew "go"
brew "hugo"
brew "lazygit"
brew "llvm"
brew "mas"
brew "ninja"
brew "node"
brew "pipenv"
brew "pipx"
brew "prettier"
brew "ripgrep"
brew "rust"
brew "rust-analyzer"
brew "starship"
brew "tectonic"
brew "zplug"
brew "dekker1/minizinc/fzn-chuffed"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "alfred"
cask "calibre"
cask "discord"
cask "docker"
cask "element"
cask "font-go"
cask "font-inter"
cask "font-victor-mono"
cask "kitty"
cask "mactex"
cask "minizincide"
cask "protonmail-bridge"
cask "protonvpn"
cask "signal"
cask "skim"
cask "sublime-merge"
cask "zoom"
mas "1Password 7", id: 1333542190
mas "GarageBand", id: 682658836
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Textual IRC Client", id: 896450579
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
