completion_type = "list"
prompt = "starship prompt"
rm_always_trash = true
table_mode = "rounded"

path = [
	"/usr/local/bin",
	"/usr/bin",
	"/bin",
	"/usr/sbin",
	"/sbin",
# From MacOS helper (/usr/libexec/path_helper)
	"/Library/TeX/texbin",
	"/Library/Apple/usr/bin",
# Terminal emulator
	"/Applications/kitty.app/Contents/MacOS",
# Homebrew binary directories
	"/opt/homebrew/bin",
	"/opt/homebrew/sbin",
]

startup = [
	"alias edit = ^($nu.env.EDITOR)",
	"alias set-light-theme = kitty +kitten themes Rose-pine-dawn",
	"alias set-dark-theme = kitty +kitten themes Rose-pine-moon",
	"alias brew-backup = brew bundle dump --global --no-lock --cask --mas --tap --force",
	"alias brew-cleanup = brew bundle cleanup --global --no-lock --force --zap",
	"alias brew-restore = brew bundle install --global --no-lock",

	# Optional binaries from Homebrew
	"pathvar add $'(brew --prefix | str trim)/opt/bison/bin'",
	"pathvar add $'(brew --prefix | str trim)/opt/flex/bin'",
	"pathvar add $'(brew --prefix | str trim)/opt/llvm/bin'",
	"pathvar add $'(brew --prefix | str trim)/opt/openjdk/bin'",

	"pathvar append ~/.local/bin", # pipx binaries
	"pathvar append ~/.cargo/bin", # cargo binaries

	"let-env MZN_SOLVER_PATH = $'(brew --prefix | str trim)/share/minizinc/solvers'",

  # Zoxide autojump
	"zoxide init nushell --hook prompt | save ~/.config/nu/zoxide.nu", "source ~/.config/nu/zoxide.nu",
]

[line_editor]
completion_match_method = "case-insensitive"
edit_mode = "vi"

[env]
# Set default editor
EDITOR = "nvim"
# Alias for Monash compute cluster
BIGBAD = "compute.optimisation-2020.cloud.edu.au"
# CMake settings
CMAKE_EXPORT_COMPILE_COMMANDS = "1" # output compile-commands.json for clangd
CMAKE_GENERATOR = "Ninja Multi-Config" # use Ninja generator by default
# Default find command for FZF
FZF_DEFAULT_COMMAND = "fd --type f"
# Homebrew shell setup (brew shellenv)
HOMEBREW_PREFIX = "/opt/homebrew"
HOMEBREW_CELLAR = "/opt/homebrew/Cellar"
HOMEBREW_REPOSITORY = "/opt/homebrew"
HOMEBREW_SHELLENV_PREFIX = "/opt/homebrew"
INFOPATH = "/opt/homebrew/share/info"
# Set MANPATH
MANPATH = "/usr/share/man:/usr/local/share/man:/Library/TeX/Distributions/.DefaultTeX/Contents/Man:/opt/homebrew/share/man"
